xebialabs/blueprints

- .github/PULL_REQUEST_TEMPLATE.md
* Splits requirement for two `README.md` files into two separate requirements: a `README.md` at the root of the blueprint and a generated `USAGE.md` in the `xebialabs` folder.
* Fixes some other typos.
> Adds requirement for USAGE.md

- aws/microservice-ecommerce/blueprint.yaml
- aws/microservice-ecommerce/cloudformation/eks-master.yaml
- aws/microservice-ecommerce/cloudformation/eks-user.yaml
- aws/microservice-ecommerce/cloudformation/eks-workers.yaml
> LOVE-777 Added app name on all resource names

- aws/datalake/blueprint.yaml
- aws/monolith-terraform/blueprint.yaml
- aws/monolith/blueprint.yaml
- devsecops/security-scanning/blueprint.yaml
- docker/simple-demo-app/blueprint.yaml
- gcp/microservice-ecommerce/blueprint.yaml
> LOVE-821 Added instructions to blueprints

- xl-devops-platform/README.md
- xl-devops-platform/__test__/answers-with-xl-release.yaml
- xl-devops-platform/__test__/answers-without-xl-release.yaml
- xl-devops-platform/__test__/test-with-xl-release.yaml
- xl-devops-platform/__test__/test-without-xl-release.yaml
- xl-devops-platform/blueprint.yaml
- xl-devops-platform/docker/data/configure-xl-devops-platform.yaml.tmpl
- xl-devops-platform/docker/docker-compose.yml.tmpl
- xl-devops-platform/xebialabs/USAGE-docker-compose.md.tmpl
- xl-devops-platform/xebialabs/config.yaml.tmpl
> Added standalone docker-compose configs

- gcp/microservice-ecommerce/__test__/answers-no-cluster-no-cicd.yaml
- gcp/microservice-ecommerce/__test__/answers-no-cluster-with-cicd.yaml
- gcp/microservice-ecommerce/__test__/answers-with-cluster-no-cicd.yaml
- gcp/microservice-ecommerce/__test__/answers-with-cluster-with-cicd.yaml
- gcp/microservice-ecommerce/blueprint.yaml
> LOVE-1024 - Made gcp/microservice-ecommerce Namespace a fixed value

- Jenkinsfile
- README.md
- Releasefile.groovy
- aws/basic-eks-cluster/blueprint.yaml
- aws/datalake/blueprint.yaml
- aws/microservice-ecommerce/blueprint.yaml
- aws/monolith-terraform/blueprint.yaml
- aws/monolith/blueprint.yaml
- azure/basic-aks-cluster/blueprint.yaml
- azure/microservice-ecommerce/blueprint.yaml
- devsecops/security-scanning/blueprint.yaml
- docker/application/blueprint.yaml
- docker/environment/blueprint.yaml
- docker/simple-demo-app/blueprint.yaml
- gcp/basic-gke-cluster/blueprint.yaml
- gcp/microservice-ecommerce/blueprint.yaml
- integration_tests.py
- kubernetes/application/blueprint.yaml
- kubernetes/environment/blueprint.yaml
- xl-devops-platform/blueprint.yaml
> LOVE-1011 Migrate Existing Blueprints to v2

- azure/app-service-docker-app/README.md
- azure/app-service-docker-app/__test__/answers-no-app.yaml
- azure/app-service-docker-app/__test__/answers-with-app.yaml
- azure/app-service-docker-app/__test__/test-no-app.yaml
- azure/app-service-docker-app/__test__/test-with-app.yaml
- azure/app-service-docker-app/blueprint.yaml
- azure/app-service-docker-app/docker/docker-compose.yml
- azure/app-service-docker-app/terraform/.gitignore
- azure/app-service-docker-app/terraform/main.tf.tmpl
- azure/app-service-docker-app/terraform/outputs.tf
- azure/app-service-docker-app/terraform/variables.tf.tmpl
- azure/app-service-docker-app/xebialabs/USAGE.md.tmpl
- azure/app-service-docker-app/xebialabs/azure-app-service.yaml.tmpl
> LOVE-751 blueprint for Azure app service

- aws/basic-eks-cluster/xebialabs/xlr-pipeline-destroy.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xlr-pipeline-destroy.yaml.tmpl
> LOVE-970 Avoid concurrent update on environment

- aws/datalake/xebialabs/xlr-pipeline.yaml.tmpl
- aws/monolith-terraform/xebialabs/xlr-pipeline.yaml.tmpl
- aws/monolith/xebialabs/xlr-pipeline.yaml.tmpl
> LOVE-703 Improve Blueprints to use the new get CI tasks

- docker/environment/README.md
> LOVE-1071 Hardening of Docker & K8s Blueprints

- aws/basic-eks-cluster/xebialabs/xld-cloudformation-apps.yaml.tmpl
- aws/basic-eks-cluster/xebialabs/xlr-pipeline-ci-cd.yaml.tmpl
- aws/basic-eks-cluster/xebialabs/xlr-pipeline-destroy.yaml.tmpl
- aws/datalake/xebialabs/xld-infrastructure.yaml.tmpl
- aws/datalake/xebialabs/xlr-pipeline.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xld-cloudformation-apps.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xlr-pipeline-ci-cd.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xlr-pipeline-destroy.yaml.tmpl
- azure/app-service-docker-app/terraform/main.tf.tmpl
- azure/app-service-docker-app/xebialabs/USAGE.md.tmpl
- azure/app-service-docker-app/xebialabs/azure-app-service.yaml.tmpl
- azure/basic-aks-cluster/blueprint.yaml
- azure/basic-aks-cluster/xebialabs/USAGE-azure-basic-aks-cluster.md.tmpl
- azure/basic-aks-cluster/xebialabs/azure-basic-aks-cluster.yaml.tmpl
- azure/microservice-ecommerce/blueprint.yaml
- azure/microservice-ecommerce/terraform/aks/main.tf
- azure/microservice-ecommerce/terraform/main.tf
- azure/microservice-ecommerce/xebialabs/xld-kubernetes-invoice-app.yaml.tmpl
- azure/microservice-ecommerce/xebialabs/xld-kubernetes-notification-app.yaml.tmpl
- azure/microservice-ecommerce/xebialabs/xld-kubernetes-store-app.yaml.tmpl
- azure/microservice-ecommerce/xebialabs/xld-terraform-apps.yaml.tmpl
- azure/microservice-ecommerce/xebialabs/xlr-pipeline-ci-cd.yaml.tmpl
- gcp/basic-gke-cluster/xebialabs/gcp-basic-gke-cluster.yaml.tmpl
- gcp/microservice-ecommerce/xebialabs/xld-kubernetes-invoice-app.yaml.tmpl
- gcp/microservice-ecommerce/xebialabs/xld-kubernetes-notification-app.yaml.tmpl
- gcp/microservice-ecommerce/xebialabs/xld-kubernetes-store-app.yaml.tmpl
- gcp/microservice-ecommerce/xebialabs/xld-terraform-apps.yaml.tmpl
- gcp/microservice-ecommerce/xebialabs/xlr-pipeline-ci-cd.yaml.tmpl
> LOVE-601 use auto created infra/env/dict

- aws/microservice-ecommerce/blueprint.yaml
- aws/microservice-ecommerce/xebialabs/xld-cloudformation-apps.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xld-kubernetes-invoice-app.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xld-kubernetes-notification-app.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xld-kubernetes-store-app.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xlr-pipeline-ci-cd.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xlr-pipeline-destroy.yaml.tmpl
> fix issues with AWS MS blueprint

- aws/basic-eks-cluster/xebialabs/aws-basic-eks-cluster-applications.yaml.tmpl
- azure/basic-aks-cluster/xebialabs/azure-basic-aks-cluster.yaml.tmpl
- gcp/basic-gke-cluster/xebialabs/gcp-basic-gke-cluster.yaml.tmpl
- kubernetes/application/xebialabs/kubernetes-application.yaml.tmpl
- kubernetes/environment/xebialabs/kubernetes-environment.yaml.tmpl
- kubernetes/multicloud-pipeline/xebialabs/multicloud-pipeline-aws.yaml.tmpl
- kubernetes/multicloud-pipeline/xebialabs/multicloud-pipeline.yaml.tmpl
> LOVE-1112 Added tag 'kubernetes-namespace'

- Releasefile.groovy
- blueprint-skeleton/README.md
- blueprint-skeleton/README.md.tmpl
- blueprint-skeleton/USAGE-skeleton.md.tmpl
- blueprint-skeleton/__test__/answers.yaml
- blueprint-skeleton/__test__/answers.yaml.tmpl
- blueprint-skeleton/__test__/test.yaml
- blueprint-skeleton/__test__/test.yaml.tmpl
- blueprint-skeleton/blueprint.yaml
- blueprint-skeleton/blueprint.yaml.tmpl
- blueprint-skeleton/xebialabs.yaml
- blueprint-skeleton/xebialabs/xld-apps.yaml.tmpl.tmpl
- blueprint-skeleton/xebialabs/xld-infra-env.yaml.tmpl.tmpl
- blueprint-skeleton/xebialabs/xlr-pipeline-ci-cd.yaml.tmpl.tmpl
- blueprint-skeleton/xebialabs/xlr-pipeline-destroy.yaml.tmpl.tmpl
> LOVE 1097 - Blueprint skeleton

- aws/basic-eks-cluster/blueprint.yaml
- aws/basic-eks-cluster/cloudformation/eks-workers.yaml.tmpl
> LOVE-1116 Update AMI for aws/basic-eks-cluster

- integration_tests.py
> LOVE-1114 Enabling default values for integration tests

- integration_tests.py
> Added --blueprints flag for more targeted integration tests

- integration_tests.py
> LOVE-1165 Fixed boolean comparison in xlvals files

- aws/basic-eks-cluster/blueprint.yaml
- aws/basic-eks-cluster/cloudformation/eks-master.yaml
- aws/basic-eks-cluster/cloudformation/eks-workers.yaml.tmpl
- aws/intermediate-eks-cluster/blueprint.yaml
- aws/intermediate-eks-cluster/cloudformation/eks-master.yaml
- aws/intermediate-eks-cluster/cloudformation/eks-workers.yaml.tmpl
- aws/microservice-ecommerce/cloudformation/eks-master.yaml
- kubernetes/multicloud-pipeline/__test__/answers-eks.yaml
> LOVE-1182 Updated K8s version from 1.10 to 1.11

- blueprint-skeleton/README.md.tmpl
- blueprint-skeleton/USAGE-skeleton.md.tmpl
- blueprint-skeleton/__test__/test.yaml.tmpl
> Small skeleton fixes

- showcases/dictionaries-and-secret-stores/blueprint.yaml
- xl-devops-platform/blueprint.yaml
> LOVE-1375 Deduplicate GenerateDockerComposeSetup

- aws/README.md
- azure/README.md
- azure/microservice-ecommerce/blueprint.yaml
- docker/README.md
- gcp/README.md
> LOVE-1336 Add common documentation for Azure, AWS, GCP, Docker, Kubernetes

- azure/README.md
- azure/microservice-ecommerce/README.md
- azure/microservice-ecommerce/blueprint.yaml
- azure/microservice-ecommerce/terraform-microservice-ecommerce/main.tf
- azure/microservice-ecommerce/xebialabs.yaml
- azure/microservice-ecommerce/xebialabs/xld-microservice-ecommerce-infra-env.yaml.tmpl
> LOVE-1399 Fixes for azure/microservice-ecommerce

- gcp/README.md
- gcp/microservice-ecommerce/__test__/test-no-cluster-no-ci-cd.yaml
- gcp/microservice-ecommerce/__test__/test-no-cluster-with-ci-cd.yaml
- gcp/microservice-ecommerce/__test__/test-with-cluster-no-ci-cd.yaml
- gcp/microservice-ecommerce/__test__/test-with-cluster-with-ci-cd.yaml
- gcp/microservice-ecommerce/blueprint.yaml
- gcp/microservice-ecommerce/manifest.yaml
- gcp/microservice-ecommerce/terraform-microservice-ecommerce/gke/main.tf
- gcp/microservice-ecommerce/terraform-microservice-ecommerce/main.tf
- gcp/microservice-ecommerce/xebialabs/USAGE-microservice-ecommerce.md.tmpl
- gcp/microservice-ecommerce/xebialabs/xlr-microservice-ecommerce-pipeline-ci-cd.yaml.tmpl
> Love 1398 - Fixes needed to deploy gcp cluster

- aws/basic-eks-cluster/README.md
- aws/basic-lambda/README.md
- aws/datalake/README.md
- aws/elastic-beanstalk/README.md
- aws/intermediate-eks-cluster/README.md
- aws/microservice-ecommerce/README.md
- aws/monolith-terraform/README.md
- aws/monolith/README.md
- azure/app-service-docker-app/README.md
- azure/basic-aks-cluster/README.md
- azure/basic-arm-template/README.md
- azure/microservice-ecommerce/README.md
- blueprint-skeleton/README.md
- devsecops/security-scanning/README.md
- gcp/basic-gke-cluster/README.md
- gcp/microservice-ecommerce/README.md
- kubernetes/environment/README.md
> LOVE-1340 Added notes for secrets.xlvals and referred to the dictionaries-and-secret-stores showcase

- aws/basic-eks-cluster/xebialabs/xld-basic-eks-cluster-applications.yaml.tmpl
- aws/microservice-ecommerce/README.md
- aws/microservice-ecommerce/blueprint.yaml
- aws/microservice-ecommerce/xebialabs/xld-microservice-ecommerce-infra-env.yaml.tmpl
- aws/microservice-ecommerce/xebialabs/xlr-microservice-ecommerce-pipeline-ci-cd.yaml.tmpl
- gcp/README.md
- gcp/microservice-ecommerce/__test__/test-no-cluster-no-ci-cd.yaml
- gcp/microservice-ecommerce/__test__/test-no-cluster-with-ci-cd.yaml
- gcp/microservice-ecommerce/__test__/test-with-cluster-no-ci-cd.yaml
- gcp/microservice-ecommerce/__test__/test-with-cluster-with-ci-cd.yaml
- gcp/microservice-ecommerce/blueprint.yaml
- gcp/microservice-ecommerce/manifest.yaml
- gcp/microservice-ecommerce/terraform-microservice-ecommerce/gke/main.tf
- gcp/microservice-ecommerce/terraform-microservice-ecommerce/main.tf
- gcp/microservice-ecommerce/xebialabs/USAGE-microservice-ecommerce.md.tmpl
- gcp/microservice-ecommerce/xebialabs/xlr-microservice-ecommerce-pipeline-ci-cd.yaml.tmpl
> LOVE-1397 Fixed to run on existing cluster

- generate_index.py
> LOVE-1558 Blueprints index.json is missing the fragments so some blueprints are failing

- azure/basic-aks-cluster/xebialabs/USAGE-basic-aks-cluster.md.tmpl
> LOVE-1508 readme documentation for aks blueprint contains a bit wrong dictionary name

- build.gradle.kts
> ENG-8955 bump release version

- build.gradle.kts
> Fix rsync command in the build process

- build.gradle.kts
> Fix job version to sync 10.2

- build.gradle.kts
> Use versionToSync to synchronize nexus to dist

- .gitignore
> update gitignore because nebula.release check
